main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('sonnyangels/', views.sonnyangels_index, name='index'),
    path('sonnyangels/<int:sonnyangel_id>', views.sonnyangels_detail, name='detail'),
    path('sonnyangels/create/', views.SonnyCreate.as_view(), name='sonnyangels_create'),
    path('sonnyangels/<int:pk>/update/', views.SonnyUpdate.as_view(), name='sonnyangels_update'),
    path('sonnyangels/<int:pk>/delete/', views.SonnyDelete.as_view(), name='sonnyangels_delete'),   
    path('sonnyangels/<int:sonnyangel_id>/add_inspect/', views.add_inspect, name='add_inspect'),
    path('sonnyangels/<int:sonnyangel_id>/assoc_outfit/<int:outfit_id>/', views.assoc_outfit, name='assoc_outfit'),
    path('sonnyangels/<int:sonnyangel_id>/assoc_outfit/<int:outfit_id>/', views.assoc_outfit, name='assoc_outfit'),
    path('sonnyangels/<int:sonnyangel_id>/unassoc_outfit/<int:outfit_id>/', views.unassoc_outfit, name='unassoc_outfit'),
    path('outfits/', views.OutfitList.as_view(), name='outfits_index'),
    path('outfits/<int:pk>/', views.OutfitDetail.as_view(), name='outfits_detail'),
    path('outfits/create/', views.OutfitCreate.as_view(), name='outfits_create'),
    path('outfits/<int:pk>/update/', views.OutfitUpdate.as_view(), name='outfits_update'),
    path('outfits/<int:pk>/delete/', views.OutfitDelete.as_view(), name='outfits_delete'),   
]

sonnyangelcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse

CONDITIONS = (
    ('N', 'Like New'),
    ('S', 'Slightly Damaged'),
    ('D', 'Damaged')
)

# Create your models here.
class Outfit(models.Model):
    type = models.CharField(max_length= 50)
    color = models.CharField(max_length= 25)

    def __str__(self):
        return self.type
    
    def get_absolute_url(self):
        return reverse('outfits_detail', kwargs={'pk': self.id})


class Sonny(models.Model):
    name = models.CharField(max_length=75)
    series = models.CharField(max_length=75)
    description = models.TextField(max_length=200)
    outfits = models.ManyToManyField(Outfit)

    def __str__(self):
        return f'{self.name} ({self.id})'
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'sonnyangel_id': self.id})
    

class Inspect(models.Model):
    date = models.DateField('Inspect Date')
    condition = models.CharField(
        max_length=1,
        choices=CONDITIONS,
        default=CONDITIONS[0][0]
    )
    sonnyangel = models.ForeignKey(Sonny, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_condition_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Inspect

class InspectForm(ModelForm):
    class Meta:
        model = Inspect
        fields = ['date', 'condition']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Sonny, Outfit
from .forms import InspectForm

# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def sonnyangels_index(request):
    sonnyangels = Sonny.objects.all()
    return render(request, 'sonnyangels/index.html', {
        'sonnyangels': sonnyangels
    })

def sonnyangels_detail(request, sonnyangel_id):
    sonnyangel = Sonny.objects.get(id=sonnyangel_id)
    id_list = sonnyangel.outfits.all().values_list('id')
    outfits_sonnyangel_doesnt_have = Outfit.objects.exclude(id__in=id_list)
    inspect_form = InspectForm()
    return render(request, 'sonnyangels/detail.html', {
        'sonnyangel': sonnyangel, 'inspect_form': inspect_form,
        'outfits': outfits_sonnyangel_doesnt_have
    })

class SonnyCreate(CreateView):
    model = Sonny
    fields = ['name', 'series', 'description']

class SonnyUpdate(UpdateView):
    model = Sonny
    fields = ['series', 'description']

class SonnyDelete(DeleteView):
    model = Sonny
    success_url = '/sonnyangels'

def add_inspect(request, sonnyangel_id):
    form = InspectForm(request.POST)
    if form.is_valid():
        new_inspect = form.save(commit=False)
        new_inspect.sonnyangel_id = sonnyangel_id
        new_inspect.save()
    return redirect('detail', sonnyangel_id=sonnyangel_id)

class OutfitList(ListView):
  model = Outfit

class OutfitDetail(DetailView):
  model = Outfit

class OutfitCreate(CreateView):
  model = Outfit
  fields = '__all__'

class OutfitUpdate(UpdateView):
  model = Outfit
  fields = ['type', 'color']

class OutfitDelete(DeleteView):
  model = Outfit
  success_url = '/outfits'

def assoc_outfit(request, sonnyangel_id, outfit_id):
  Sonny.objects.get(id=sonnyangel_id).outfits.add(outfit_id)
  return redirect('detail', sonnyangel_id=sonnyangel_id)

def unassoc_outfit(request, sonnyangel_id, outfit_id):
  Sonny.objects.get(id=sonnyangel_id).outfits.remove(outfit_id)
  return redirect('detail', sonnyangel_id=sonnyangel_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h1>About the Sonny Angel Collector</h1>
    <hr>
    <p><strong>Become a Sonny Angel Collector! Sonny Angels are baby angel figurines with different themes from animals to veggies and even some rare collections, collect them all!</strong></p>
    <h6><strong>Discover, Organize, and Showcase Your Collection</strong></h6>
<p>Gone are the days of managing your Sonny Angel collection with spreadsheets and photos scattered across various devices. Our app is designed to help you effortlessly keep track of your treasured figurines. You can catalog each Sonny Angel individually, including their series, rarity, and acquisition details. </p>
<h6><strong>Quality Inspections Made Simple</strong></h6>
<p>Quality is paramount when it comes to Sonny Angel figurines. Our app streamlines the quality inspection process, allowing you to keep meticulous records of each angel's condition. Note any imperfections, such as paint chips, scuffs, or defects, and maintain a comprehensive history of their condition over time. Stay confident in the authenticity and quality of your collection.</p>
<h6><strong>Experice The Joy of Sonny Angel Collecting</strong></h6>
<p>At Sonny Angel Collector App, we understand that collecting these delightful figurines is more than a hobby; it's a joyful and fulfilling experience. Whether you're adding to your collection, designing unique outfits, or meticulously inspecting your angels, our app is your trusted companion on this whimsical journey.

    Join us in celebrating the world of Sonny Angel collecting, where creativity, community, and quality converge. Start documenting your collection and designing incredible outfits. Let's make your Sonny Angel collecting experience even more enchanting and unforgettable.</p>
    <footer>All Rights Reserved, &copy; 2023 Sonny Angel Collector</footer>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Sonny Angel Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Sonny Angel Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'outfits_create' %}">Add an Outfit</a></li>
          <li><a href="{% url 'outfits_index' %}">View All Outfits</a></li>
          <li><a href="{% url 'sonnyangels_create' %}">Add a Sonny Angel</a></li>
          <li><a href="{% url 'index' %}">View All My Sonny Angels</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2023 Sonny Angel Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>
<hr>
<h5>✨Welcome to the Sonny Angel Collector! Where you can keep track
    of all your sonny angels in one place and watch your collection grow. Add any outfits you have created for your angels
    and even keep a log of your sonny angels condition inspections, happy collecting!✨
</h5>
<h6><strong>Discover, Organize, and Showcase Your Collection</strong></h6>
<p>Gone are the days of managing your Sonny Angel collection with spreadsheets and photos scattered across various devices. Our app is designed to help you effortlessly keep track of your treasured figurines. You can catalog each Sonny Angel individually, including their series, rarity, and acquisition details. </p>
<h6><strong>Quality Inspections Made Simple</strong></h6>
<p>Quality is paramount when it comes to Sonny Angel figurines. Our app streamlines the quality inspection process, allowing you to keep meticulous records of each angel's condition. Note any imperfections, such as paint chips, scuffs, or defects, and maintain a comprehensive history of their condition over time. Stay confident in the authenticity and quality of your collection.</p>
<h6><strong>Experice The Joy of Sonny Angel Collecting</strong></h6>
<p>At Sonny Angel Collector App, we understand that collecting these delightful figurines is more than a hobby; it's a joyful and fulfilling experience. Whether you're adding to your collection, designing unique outfits, or meticulously inspecting your angels, our app is your trusted companion on this whimsical journey.

    Join us in celebrating the world of Sonny Angel collecting, where creativity, community, and quality converge. Start documenting your collection and designing incredible outfits. Let's make your Sonny Angel collecting experience even more enchanting and unforgettable.</p>
{% endblock %}

main_app/templates/main_app/outfit_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Outfit</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'outfits_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/outfit_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Outfit Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ outfit.type }}</span>
        <p>Color: {{ outfit.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'outfits_update' outfit.id %}">Edit</a>
        <a href="{% url 'outfits_delete' outfit.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/outfit_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Outfit</h1>
  {% endif %}
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/outfit_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Outfit List</h1>

{% for outfit in outfit_list %}
  <a href="{% url 'outfits_detail' outfit.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ outfit.type }}</span>
            <p>Color: {{ outfit.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/sonny_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Sonny Angel</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' sonnyangel.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/sonny_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
{% else %}
    <h1>Add Sonny Angel</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit the Angel!" class="btn">
</form>

{% endblock %}

main_app/templates/sonnyangels/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Sonny Angel Details</h1>
<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ sonnyangel.name }}</span>
        <p>Series: {{ sonnyangel.series }}</p>
        <p>Description: {{ sonnyangel.description|linebreaks }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'sonnyangels_update' sonnyangel.id %}">Edit</a>
        <a href="{% url 'sonnyangels_delete' sonnyangel.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_inspect' sonnyangel.id %}" method="POST">
      {% csrf_token %}
      {{ inspect_form.as_p }}
      <input type="submit" class="btn" value="Add Inspection">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Inspection</th></tr>
      </thead>
      <tbody>
        {% for inspect in sonnyangel.inspect_set.all %}
          <tr>
            <td>{{inspect.date}}</td>
            <td>{{inspect.get_condition_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ sonnyangel.name }}'s Outfits</h3>
    {% if sonnyangel.outfits.count %}
      {% for outfit in sonnyangel.outfits.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span style="color: {{ outfit.color }}">{{ outfit.color }}</span> {{ outfit.type }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'unassoc_outfit' sonnyangel.id outfit.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Outfits🫢</h5>
    {% endif %}
  </div>
  <!-- Available outfits will come after this line -->
  <div class="col s6">
    <h3>Available Fits</h3>
    {% if outfits.count %}
      {% for outfit in outfits.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span style="color: {{ outfit.color }}">{{ outfit.color }}</span> {{ outfit.type }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_outfit' sonnyangel.id outfit.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{sonnyangel.name}} Already Has All Fits Available</h5>
    {% endif %}
  </div>

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  }); 

  const selectEl = document.getElementById('id_condition');
  M.FormSelect.init(selectEl);

</script>

{% endblock %}

main_app/templates/sonnyangels/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Sonny Angels List</h1>

{% for sonnyangel in sonnyangels %}
  <div class="card">
    <a href="/sonnyangels/{{ sonnyangel.id }}">
      <div class="card-content">
        <span class="card-title">{{ sonnyangel.name }}</span>
        <p>Series: {{ sonnyangel.series }}</p>
        <p>Description: {{ sonnyangel.description|linebreaks }}</p>
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}